version: '3.8'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  myapp:
    container_name: aiohttp_api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "always"
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    networks:
      - app_network

networks:
  app_network:
    external: false
    name: app_network
